package com.example.demo.entity;

import java.time.LocalDateTime;
import java.util.Date;

public class TUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_name
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.age
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.sex
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.memo
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.create_datetime
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.upadte_datetime
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private Date upadteDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.pwd
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_name
     *
     * @return the value of t_user_info.user_name
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_name
     *
     * @param userName the value for t_user_info.user_name
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.age
     *
     * @return the value of t_user_info.age
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.age
     *
     * @param age the value for t_user_info.age
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.sex
     *
     * @return the value of t_user_info.sex
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.sex
     *
     * @param sex the value for t_user_info.sex
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.memo
     *
     * @return the value of t_user_info.memo
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.memo
     *
     * @param memo the value for t_user_info.memo
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.create_datetime
     *
     * @return the value of t_user_info.create_datetime
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public LocalDateTime getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.create_datetime
     *
     * @param createDatetime the value for t_user_info.create_datetime
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setCreateDatetime(LocalDateTime createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.upadte_datetime
     *
     * @return the value of t_user_info.upadte_datetime
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public Date getUpadteDatetime() {
        return upadteDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.upadte_datetime
     *
     * @param upadteDatetime the value for t_user_info.upadte_datetime
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setUpadteDatetime(Date upadteDatetime) {
        this.upadteDatetime = upadteDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.pwd
     *
     * @return the value of t_user_info.pwd
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.pwd
     *
     * @param pwd the value for t_user_info.pwd
     *
     * @mbg.generated Thu Oct 13 16:10:02 CST 2022
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
}